#
# This is the default Travis CI configuration.
#
# It uses a GitHub OAuth token when fetching composer dependencies
# to avoid IP-based API throttling.
#
# It also allows publication of artifacts via an additional build.
#
language: php

php: ["5.3", "5.4", "5.5"]

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.4
    - secure: "vvyxNXKp97/RTGiPZfHUqP0muR1O60B/UJfsAPdiA8NZ/hDNyF9rM1rJzoZBw5ffgYRBjvnY8Tw0QP8KIJ9vp80B//KECC3y3zs3J8WXEKyk1iL+tVkdwS3ZSyhcEfHkk2STyLo1mig215fKj0SgOCUu3tE+myEmMEXisS8DRLc="

install:
  - ./.travis.install
script:
  - ./vendor/bin/archer travis:build
